# Generated by Django 4.2.7 on 2023-12-08 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Admin')),
                ('Username', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100, unique=True)),
                ('Password', models.CharField(blank=True, max_length=8)),
                ('Token', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Relay')),
                ('Tension', models.FloatField(default=0)),
                ('Courant', models.FloatField(default=0)),
                ('Puissance', models.FloatField(default=0)),
                ('Energie', models.FloatField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('Temps', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 10, 12, 38, 628849))),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Relay')),
                ('Value', models.BooleanField(default=False)),
            ],
        ),
    ]
